/* Generated By:JavaCC: Do not edit this line. RuleParserConstants.java */
public interface RuleParserConstants {

  int EOF = 0;
  int RULE = 8;
  int CLASS = 9;
  int OBJ = 10;
  int IF = 11;
  int THEN = 12;
  int MODIFY = 13;
  int MAKE = 14;
  int MAKET = 15;
  int REMOVE = 16;
  int PRINT = 17;
  int READ = 18;
  int PROMPT = 19;
  int BIND = 20;
  int VAR = 21;
  int EXECUTE = 22;
  int DISPLAY = 23;
  int TYPE = 24;
  int OR = 25;
  int AND = 26;
  int GT = 27;
  int GE = 28;
  int LT = 29;
  int LE = 30;
  int EQ = 31;
  int NE = 32;
  int MODULE = 33;
  int STRUCT = 34;
  int STRING = 35;
  int LONG = 36;
  int DOUBLE = 37;
  int FLOAT = 38;
  int IDENTIFIER = 39;
  int LETTER = 40;
  int DIGIT = 41;
  int INTEGER_LITERAL = 42;
  int DECIMAL_LITERAL = 43;
  int HEX_LITERAL = 44;
  int OCTAL_LITERAL = 45;
  int FLOATING_POINT_LITERAL = 46;
  int EXPONENT = 47;
  int CHARACTER_LITERAL = 48;
  int STRING_LITERAL = 49;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<token of kind 7>",
    "\"RULE\"",
    "\"CLASS\"",
    "\"OBJ\"",
    "\"IF\"",
    "\"THEN\"",
    "\"MODIFY\"",
    "\"MAKE\"",
    "\"MAKET\"",
    "\"REMOVE\"",
    "\"PRINT\"",
    "\"READ\"",
    "\"PROMPT\"",
    "\"BIND\"",
    "\"VAR\"",
    "\"EXECUTE\"",
    "\"DISPLAY\"",
    "\"TYPE\"",
    "<OR>",
    "<AND>",
    "<GT>",
    "<GE>",
    "<LT>",
    "<LE>",
    "<EQ>",
    "<NE>",
    "\"module\"",
    "\"struct\"",
    "\"string\"",
    "\"long\"",
    "\"double\"",
    "\"float\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\"(\"",
    "\":\"",
    "\")\"",
    "\"$\"",
    "\",\"",
    "\"|\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
  };

}
