package MemoryServer;


/**
* MemoryServer/WMGetSetObject.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ./MemoryServer.idl
* Friday, March 12, 2004 3:16:53 PM EST
*/

public interface WMGetSetObject extends WMGetSetObjectOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface WMGetSetObject
