package MemoryServer;

/**
* MemoryServer/WMGetSetObjectHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from MemoryServer.idl
* Thursday, February 12, 2004 11:11:32 AM EST
*/

public final class WMGetSetObjectHolder implements org.omg.CORBA.portable.Streamable
{
  public MemoryServer.WMGetSetObject value = null;

  public WMGetSetObjectHolder ()
  {
  }

  public WMGetSetObjectHolder (MemoryServer.WMGetSetObject initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MemoryServer.WMGetSetObjectHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MemoryServer.WMGetSetObjectHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MemoryServer.WMGetSetObjectHelper.type ();
  }

}
