package ReteObjects;


/**
* ReteObjects/COSMOS_START.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from crime.idl
* Thursday, February 12, 2004 11:11:30 AM EST
*/

public final class COSMOS_START implements org.omg.CORBA.portable.IDLEntity
{
  public int init_status = (int)0;

  public COSMOS_START ()
  {
  } // ctor

  public COSMOS_START (int _init_status)
  {
    init_status = _init_status;
  } // ctor

} // class COSMOS_START
