package MemoryServer;


/**
* MemoryServer/WMGetSetObject.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from MemoryServer.idl
* Monday, April 12, 2004 12:29:12 PM EDT
*/

public interface WMGetSetObject extends WMGetSetObjectOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface WMGetSetObject
