package ReteObjects;


/**
* ReteObjects/container.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ReteObjects.idl
* Friday, March 12, 2004 3:45:26 PM EST
*/

public final class container implements org.omg.CORBA.portable.IDLEntity
{
  public double variable1 = (double)0;
  public float P_H_Ep_variable1 = (float)0;
  public double variable2 = (double)0;
  public float P_H_Ep_variable2 = (float)0;
  public double variable3 = (double)0;
  public float P_H_Ep_variable3 = (float)0;

  public container ()
  {
  } // ctor

  public container (double _variable1, float _P_H_Ep_variable1, double _variable2, float _P_H_Ep_variable2, double _variable3, float _P_H_Ep_variable3)
  {
    variable1 = _variable1;
    P_H_Ep_variable1 = _P_H_Ep_variable1;
    variable2 = _variable2;
    P_H_Ep_variable2 = _P_H_Ep_variable2;
    variable3 = _variable3;
    P_H_Ep_variable3 = _P_H_Ep_variable3;
  } // ctor

} // class container
