package ReteObjects;


/**
* ReteObjects/COSMOS_START.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ReteObjects.idl
* Wednesday, May 19, 2004 2:25:01 PM EDT
*/

public final class COSMOS_START implements org.omg.CORBA.portable.IDLEntity
{
  public int init_status = (int)0;
  public float P_H_Ep_init_status = (float)0;

  public COSMOS_START ()
  {
  } // ctor

  public COSMOS_START (int _init_status, float _P_H_Ep_init_status)
  {
    init_status = _init_status;
    P_H_Ep_init_status = _P_H_Ep_init_status;
  } // ctor

} // class COSMOS_START
