package ReteObjects;


/**
* ReteObjects/Crime.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ReteObjects.idl
* Thursday, February 12, 2004 5:35:30 PM EST
*/

public final class Crime implements org.omg.CORBA.portable.IDLEntity
{
  public String InBedroom = null;
  public String InDressingRoom = null;
  public String InStudy = null;
  public String CrimeInPrivateDomain = null;
  public String VictimeKnewAndTrustedKiller = null;

  public Crime ()
  {
  } // ctor

  public Crime (String _InBedroom, String _InDressingRoom, String _InStudy, String _CrimeInPrivateDomain, String _VictimeKnewAndTrustedKiller)
  {
    InBedroom = _InBedroom;
    InDressingRoom = _InDressingRoom;
    InStudy = _InStudy;
    CrimeInPrivateDomain = _CrimeInPrivateDomain;
    VictimeKnewAndTrustedKiller = _VictimeKnewAndTrustedKiller;
  } // ctor

} // class Crime
