package ReteObjects;

/**
* ReteObjects/mechanicHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ReteObjects.idl
* Wednesday, May 19, 2004 2:25:01 PM EDT
*/

public final class mechanicHolder implements org.omg.CORBA.portable.Streamable
{
  public ReteObjects.mechanic value = null;

  public mechanicHolder ()
  {
  }

  public mechanicHolder (ReteObjects.mechanic initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ReteObjects.mechanicHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ReteObjects.mechanicHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ReteObjects.mechanicHelper.type ();
  }

}
