package ReteObjects;


/**
* ReteObjects/mechanicHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ReteObjects.idl
* Wednesday, May 19, 2004 2:25:01 PM EDT
*/

abstract public class mechanicHelper
{
  private static String  _id = "IDL:ReteObjects/mechanic:1.0";

  public static void insert (org.omg.CORBA.Any a, ReteObjects.mechanic that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ReteObjects.mechanic extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "first_name",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_float);
          _members0[1] = new org.omg.CORBA.StructMember (
            "P_H_Ep_first_name",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (ReteObjects.mechanicHelper.id (), "mechanic", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ReteObjects.mechanic read (org.omg.CORBA.portable.InputStream istream)
  {
    ReteObjects.mechanic value = new ReteObjects.mechanic ();
    value.first_name = istream.read_string ();
    value.P_H_Ep_first_name = istream.read_float ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ReteObjects.mechanic value)
  {
    ostream.write_string (value.first_name);
    ostream.write_float (value.P_H_Ep_first_name);
  }

}
