package ReteObjects;


/**
* ReteObjects/mechanic.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ReteObjects.idl
* Wednesday, May 19, 2004 2:25:01 PM EDT
*/

public final class mechanic implements org.omg.CORBA.portable.IDLEntity
{
  public String first_name = null;
  public float P_H_Ep_first_name = (float)0;

  public mechanic ()
  {
  } // ctor

  public mechanic (String _first_name, float _P_H_Ep_first_name)
  {
    first_name = _first_name;
    P_H_Ep_first_name = _P_H_Ep_first_name;
  } // ctor

} // class mechanic
