package ReteObjects;


/**
* ReteObjects/COSMOS_START.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from test1.idl
* Friday, March 12, 2004 3:16:51 PM EST
*/

public final class COSMOS_START implements org.omg.CORBA.portable.IDLEntity
{
  public int init_status = (int)0;
  public float _P_H_Ep_init_status = (float)0;

  public COSMOS_START ()
  {
  } // ctor

  public COSMOS_START (int _init_status, float __P_H_Ep_init_status)
  {
    init_status = _init_status;
    _P_H_Ep_init_status = __P_H_Ep_init_status;
  } // ctor

} // class COSMOS_START
