package MemoryServer;


/**
* MemoryServer/WMGetSetObject.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from MemoryServer.idl
* Thursday, February 12, 2004 11:11:32 AM EST
*/

public interface WMGetSetObject extends WMGetSetObjectOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface WMGetSetObject
