package MemoryServer;


/**
* MemoryServer/WMGetSetObjectOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./MemoryServer.idl
* czwartek, 15 wrzesieñ 2005 13:47:26 CEST
*/

public interface WMGetSetObjectOperations 
{
  void WMSetObject (org.omg.CORBA.Any obj, String name);
  void WMDeleteObject (String name);
  void WMGetObject (int tin, org.omg.CORBA.IntHolder tmax, org.omg.CORBA.StringHolder on, org.omg.CORBA.AnyHolder obj);
  void WMWaitForChange (int ti);
  void WMGetItem (int index, org.omg.CORBA.StringHolder name);
} // interface WMGetSetObjectOperations
