package MemoryServer;


/**
* MemoryServer/WMGetSetObject.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./MemoryServer.idl
* czwartek, 15 wrzesieñ 2005 13:47:26 CEST
*/

public interface WMGetSetObject extends WMGetSetObjectOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface WMGetSetObject
