package ReteObjects;


/**
* ReteObjects/car.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from car.idl
* czwartek, 15 wrzesieñ 2005 13:34:43 CEST
*/

public final class car implements org.omg.CORBA.portable.IDLEntity
{
  public String problem = null;
  public float _P_H_Ep_problem = (float)0;
  public String init_problem = null;
  public float _P_H_Ep_init_problem = (float)0;
  public String headlights = null;
  public float _P_H_Ep_headlights = (float)0;
  public String spark_plug_spark = null;
  public float _P_H_Ep_spark_plug_spark = (float)0;
  public String fuel_gauge_reading = null;
  public float _P_H_Ep_fuel_gauge_reading = (float)0;
  public String carburetor_gas = null;
  public float _P_H_Ep_carburetor_gas = (float)0;
  public String ignition_key = null;
  public float _P_H_Ep_ignition_key = (float)0;
  public String engine_turning_over = null;
  public float _P_H_Ep_engine_turning_over = (float)0;
  public String vehicle_make = null;
  public float _P_H_Ep_vehicle_make = (float)0;

  public car ()
  {
  } // ctor

  public car (String _problem, float __P_H_Ep_problem, String _init_problem, float __P_H_Ep_init_problem, String _headlights, float __P_H_Ep_headlights, String _spark_plug_spark, float __P_H_Ep_spark_plug_spark, String _fuel_gauge_reading, float __P_H_Ep_fuel_gauge_reading, String _carburetor_gas, float __P_H_Ep_carburetor_gas, String _ignition_key, float __P_H_Ep_ignition_key, String _engine_turning_over, float __P_H_Ep_engine_turning_over, String _vehicle_make, float __P_H_Ep_vehicle_make)
  {
    problem = _problem;
    _P_H_Ep_problem = __P_H_Ep_problem;
    init_problem = _init_problem;
    _P_H_Ep_init_problem = __P_H_Ep_init_problem;
    headlights = _headlights;
    _P_H_Ep_headlights = __P_H_Ep_headlights;
    spark_plug_spark = _spark_plug_spark;
    _P_H_Ep_spark_plug_spark = __P_H_Ep_spark_plug_spark;
    fuel_gauge_reading = _fuel_gauge_reading;
    _P_H_Ep_fuel_gauge_reading = __P_H_Ep_fuel_gauge_reading;
    carburetor_gas = _carburetor_gas;
    _P_H_Ep_carburetor_gas = __P_H_Ep_carburetor_gas;
    ignition_key = _ignition_key;
    _P_H_Ep_ignition_key = __P_H_Ep_ignition_key;
    engine_turning_over = _engine_turning_over;
    _P_H_Ep_engine_turning_over = __P_H_Ep_engine_turning_over;
    vehicle_make = _vehicle_make;
    _P_H_Ep_vehicle_make = __P_H_Ep_vehicle_make;
  } // ctor

} // class car
