package ReteObjects;

/**
* ReteObjects/COSMOS_STARTHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from car.idl
* czwartek, 15 wrzesieñ 2005 13:34:43 CEST
*/

public final class COSMOS_STARTHolder implements org.omg.CORBA.portable.Streamable
{
  public ReteObjects.COSMOS_START value = null;

  public COSMOS_STARTHolder ()
  {
  }

  public COSMOS_STARTHolder (ReteObjects.COSMOS_START initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ReteObjects.COSMOS_STARTHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ReteObjects.COSMOS_STARTHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ReteObjects.COSMOS_STARTHelper.type ();
  }

}
