package ReteObjects;


/**
* ReteObjects/COSMOS_START.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from car.idl
* czwartek, 15 wrzesieñ 2005 13:34:43 CEST
*/

public final class COSMOS_START implements org.omg.CORBA.portable.IDLEntity
{
  public int init_status = (int)0;
  public float _P_H_Ep_init_status = (float)0;

  public COSMOS_START ()
  {
  } // ctor

  public COSMOS_START (int _init_status, float __P_H_Ep_init_status)
  {
    init_status = _init_status;
    _P_H_Ep_init_status = __P_H_Ep_init_status;
  } // ctor

} // class COSMOS_START
