package ReteObjects;

/**
* ReteObjects/mechanicHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from car.idl
* czwartek, 15 wrzesieñ 2005 13:34:43 CEST
*/

public final class mechanicHolder implements org.omg.CORBA.portable.Streamable
{
  public ReteObjects.mechanic value = null;

  public mechanicHolder ()
  {
  }

  public mechanicHolder (ReteObjects.mechanic initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ReteObjects.mechanicHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ReteObjects.mechanicHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ReteObjects.mechanicHelper.type ();
  }

}
