package ReteObjects;


/**
* ReteObjects/mechanic.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from car.idl
* czwartek, 15 wrzesieñ 2005 13:34:43 CEST
*/

public final class mechanic implements org.omg.CORBA.portable.IDLEntity
{
  public String first_name = null;
  public float _P_H_Ep_first_name = (float)0;

  public mechanic ()
  {
  } // ctor

  public mechanic (String _first_name, float __P_H_Ep_first_name)
  {
    first_name = _first_name;
    _P_H_Ep_first_name = __P_H_Ep_first_name;
  } // ctor

} // class mechanic
